const SHOPIFY=window.FRRIDAY_SHOPIFY,$=s=>document.querySelector(s);const id=()=>localStorage.getItem('frriday-cart-id');
const Q=`query Cart($id:ID!){cart(id:$id){id checkoutUrl totalQuantity cost{totalAmount{amount currencyCode}} lines(first:100){nodes{id quantity cost{totalAmount{amount currencyCode}} merchandise{... on ProductVariant{id title product{title handle featuredImage{url altText}}}}}}}}`;
const MUT=`mutation Update($cartId:ID!,$lines:[CartLineUpdateInput!]!){cartLinesUpdate(cartId:$cartId,lines:$lines){cart{id checkoutUrl totalQuantity cost{totalAmount{amount currencyCode}} lines(first:100){nodes{id quantity cost{totalAmount{amount currencyCode}} merchandise{... on ProductVariant{id title product{title handle featuredImage{url altText}}}}}}}userErrors{message}}}`;
async function request(query,variables={}){const r=await fetch(SHOPIFY.endpoint,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({query,variables})});const j=await r.json().catch(()=>({}));if(!r.ok||j.errors?.length)throw new Error(j.errors?.map(e=>e.message).join('; ')||j.error||`Shopify returned ${r.status}`);return j.data;}
function money(x){return new Intl.NumberFormat('en-US',{style:'currency',currency:x.currencyCode,maximumFractionDigits:0}).format(+x.amount)}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function save(c){localStorage.setItem('frriday-cart-count',String(c.totalQuantity||0));$('#bagCount').textContent=c.totalQuantity||0;$('#subtotal').textContent=money(c.cost.totalAmount);$('#checkout').disabled=!c.checkoutUrl;$('#checkout').onclick=()=>location.href=c.checkoutUrl;}
async function update(lineId,qty){const cartId=id();const d=await request(MUT,{cartId,lines:[{id:lineId,quantity:qty}]});const x=d.cartLinesUpdate;if(x.userErrors?.length)throw new Error(x.userErrors.map(e=>e.message).join('; '));save(x.cart);render(x.cart);}
function render(c){const wrap=$('#bagItems');if(!c?.lines?.nodes?.length){wrap.innerHTML='<div class="bag-empty"><span class="eyebrow">BAG / EMPTY</span><h2>Nothing<br>selected.</h2><p>Your next piece is waiting.</p><a class="pill dark-pill" href="/shop.html">Shop the collection <span>↗</span></a></div>';save(c||{totalQuantity:0,cost:{totalAmount:{amount:0,currencyCode:'USD'}}});return;}wrap.innerHTML=c.lines.nodes.map(l=>{const m=l.merchandise,p=m.product;return `<article class="bag-item"><a class="bag-item-media" href="/products/${encodeURIComponent(p.handle)}"><img src="${esc(p.featuredImage?.url||'')}" alt="${esc(p.featuredImage?.altText||p.title)}"></a><div><h3>${esc(p.title.replace(/^Unisex\s+/i,''))}</h3><p>${esc(m.title)}</p><div class="bag-actions"><div class="bag-qty"><button data-line="${l.id}" data-change="-1">−</button><span>${l.quantity}</span><button data-line="${l.id}" data-change="1">+</button></div><button class="remove" data-line="${l.id}" data-remove="1">Remove</button></div></div><strong class="bag-price">${money(l.cost.totalAmount)}</strong></article>`}).join('');wrap.querySelectorAll('[data-change]').forEach(b=>b.onclick=async()=>{try{const line=c.lines.nodes.find(x=>x.id===b.dataset.line);await update(line.id,Math.max(0,line.quantity+Number(b.dataset.change)))}catch(e){alert(e.message)}});wrap.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{try{await update(b.dataset.line,0)}catch(e){alert(e.message)}});save(c);}
(async()=>{try{const cartId=id();if(!cartId){render(null);return}const d=await request(Q,{id:cartId});if(!d.cart){localStorage.removeItem('frriday-cart-id');render(null);return}render(d.cart);}catch(e){console.error(e);$('#bagItems').innerHTML='<div class="bag-empty"><span class="eyebrow">BAG / ERROR</span><h2>We hit a snag.</h2><p>Please refresh and try again.</p></div>';}})();